# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrimTabMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TrimTabMessages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15TrimTabMessages.proto\"\xbc\x01\n\tTrimState\x12\x15\n\rcontrol_angle\x18\x01 \x01(\r\x12$\n\x05state\x18\x02 \x01(\x0e\x32\x15.TrimState.TRIM_STATE\"r\n\nTRIM_STATE\x12\x11\n\rMAX_LIFT_PORT\x10\x00\x12\x11\n\rMAX_LIFT_STBD\x10\x01\x12\x11\n\rMAX_DRAG_PORT\x10\x02\x12\x11\n\rMAX_DRAG_STBD\x10\x03\x12\x0c\n\x08MIN_LIFT\x10\x04\x12\n\n\x06MANUAL\x10\x05\"*\n\x11\x41pparentWind_Trim\x12\x15\n\rapparent_wind\x18\x01 \x01(\x02\x62\x06proto3')
)



_TRIMSTATE_TRIM_STATE = _descriptor.EnumDescriptor(
  name='TRIM_STATE',
  full_name='TrimState.TRIM_STATE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MAX_LIFT_PORT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_LIFT_STBD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_DRAG_PORT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_DRAG_STBD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIN_LIFT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=100,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_TRIMSTATE_TRIM_STATE)


_TRIMSTATE = _descriptor.Descriptor(
  name='TrimState',
  full_name='TrimState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_angle', full_name='TrimState.control_angle', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='TrimState.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRIMSTATE_TRIM_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=214,
)


_APPARENTWIND_TRIM = _descriptor.Descriptor(
  name='ApparentWind_Trim',
  full_name='ApparentWind_Trim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apparent_wind', full_name='ApparentWind_Trim.apparent_wind', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=258,
)

_TRIMSTATE.fields_by_name['state'].enum_type = _TRIMSTATE_TRIM_STATE
_TRIMSTATE_TRIM_STATE.containing_type = _TRIMSTATE
DESCRIPTOR.message_types_by_name['TrimState'] = _TRIMSTATE
DESCRIPTOR.message_types_by_name['ApparentWind_Trim'] = _APPARENTWIND_TRIM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrimState = _reflection.GeneratedProtocolMessageType('TrimState', (_message.Message,), dict(
  DESCRIPTOR = _TRIMSTATE,
  __module__ = 'TrimTabMessages_pb2'
  # @@protoc_insertion_point(class_scope:TrimState)
  ))
_sym_db.RegisterMessage(TrimState)

ApparentWind_Trim = _reflection.GeneratedProtocolMessageType('ApparentWind_Trim', (_message.Message,), dict(
  DESCRIPTOR = _APPARENTWIND_TRIM,
  __module__ = 'TrimTabMessages_pb2'
  # @@protoc_insertion_point(class_scope:ApparentWind_Trim)
  ))
_sym_db.RegisterMessage(ApparentWind_Trim)


# @@protoc_insertion_point(module_scope)
